# Generated by Django 3.2.25 on 2026-01-15 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj_mgmt_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(),
        ),
    ]
