# Generated by Django 3.2.25 on 2026-01-15 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj_mgmt_api', '0002_alter_project_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('to_do', 'To Do'), ('in_progress', 'In Progress'), ('done', 'Done')], max_length=20),
        ),
    ]
